# Generated by Django 6.0 on 2025-12-21 03:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorImpacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "impacto_porcentaje",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TECNICO", "Técnico"),
                            ("OPERATIVO", "Operativo"),
                            ("HUMANO", "Recursos Humanos"),
                            ("CLIENTE", "Cliente"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KPIMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ADHERENCIA", "Adherencia"),
                            ("SERVICIO", "Nivel de Servicio"),
                            ("SATISFACCION", "Satisfacción"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("PT", "Part-Time"),
                            ("FT", "Full-Time"),
                            ("TEMP", "Temporal"),
                        ],
                        max_length=4,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("fecha_ingreso", models.DateField()),
                ("horas_semana", models.IntegerField(default=40)),
                ("activo", models.BooleanField(default=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("turno", models.CharField(max_length=50)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "horas_planificadas",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "pausas_planificadas",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programas",
                        to="dashboard.agente",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora_inicio"],
                "unique_together": {("agente", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="RegistroActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.DateTimeField()),
                ("hora_fin", models.DateTimeField()),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("LLAMADA", "En llamada"),
                            ("PAUSA", "Pausa activa"),
                            ("DISPO", "Disponible"),
                            ("CAPAC", "Capacitación"),
                            ("REUNION", "Reunión"),
                            ("ADMIN", "Tareas administrativas"),
                            ("ALMUERZO", "Almuerzo"),
                            ("AUSENTE", "Ausente"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duracion_minutos", models.IntegerField()),
                ("llamadas_atendidas", models.IntegerField(default=0)),
                ("tiempo_conversacion", models.IntegerField(default=0)),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="dashboard.agente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-hora_inicio"],
                "indexes": [
                    models.Index(
                        fields=["agente", "fecha"],
                        name="dashboard_r_agente__7b30a4_idx",
                    ),
                    models.Index(
                        fields=["tipo_actividad", "fecha"],
                        name="dashboard_r_tipo_ac_b943e6_idx",
                    ),
                ],
            },
        ),
    ]
